version: "3"

services:
  ctforces-django:
    build:
      context: .
      dockerfile: ./configs/django.Dockerfile
    volumes:
    - ./volumes/static:/static
    - ./volumes/socks:/socks
    - ./volumes/server_logs:/logs
    depends_on:
    - ctforces-postgres
    restart: on-failure
    container_name: ctforces-django-main

  ctforces-nginx:
    image: nginx
    volumes:
    - ./configs/nginx.conf:/etc/nginx/nginx.conf
    - ./configs/nginx.proxy_params:/etc/nginx/proxy_params
    - ./volumes/static:/static:ro
    - ./volumes/socks:/socks
    depends_on:
    - ctforces-django
    ports:
    - "8000:80"
    restart: on-failure
    container_name: ctforces-nginx-main

  ctforces-postgres:
    image: postgres
    volumes:
    - ./volumes/db:/var/lib/postgresql/data
    restart: on-failure
    container_name: ctforces-postgres-main
